### ISSUE TITLE
Allow users to skip questions while doing a meeting/survey

### ISSUE THREAD

**Issue by codespook** [impactasaurus/app#105]
Currently the users are forced to answer a question before moving on to the next one. I think that they should be allowed to skip questions if they want to. I've come across this feature in most surveys that can be taken online. Currently, the users can skip a question by clicking on some other tab, for eg. 'Home' or 'Review' but this would lead to that meeting being abandoned.

**Comment by drimpact** [comment]
An interesting requirement and one I think will be useful for users. 

I know for most question sets we deal with at the moment, they would not want beneficiaries skipping questions as it would mess up their evaluation of the individual. So I think it should be optional, defaulting to not allowing skipping.

I will add a server issue to allow question sets to be defined as allowing question skipping or not. This will block this change.

**Comment by drimpact** [comment]
The backend has been adjusted to add a `skippable` attribute to outcomesets. If this is true, questions can be skipped.

**Comment by drimpact** [comment]
Decided not to implement this for the time being
