### ISSUE TITLE
Assessment list for beneficiary

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#108]
There is multiple requirements which allow a beneficiary's previous assessments to be listed. This allow #31, #18 and #8. This issue should get a list in place somewhere in the app so that the other issues can build on top of this list.

 - Think about where this should be put within the app (discuss with @drimpact)
 - Implement list displaying assessments, for each display date (actual rather than semantic) and number of questions completed

**Comment by drimpact** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Assessment management](https://trello.com/c/UQUYQHKI/26-assessment-management)

**Comment by nikw92** [comment]
Just to be clear when you say 'assessments' you mean 'meetings' right? 

If so, I would like to suggest that we settle on calling them 'surveys' because that's what they are essentially in their current state, unless you plan on expanding their definition in the future by adding various features. It just removes the potential ambiguity and makes it less likely for users to confuse them for something else, in my opinion.

**Comment by drimpact** [comment]
Yea assessment == meeting. 

I am still getting the nomenclature correct, but from talking to charities, it seems assessment is the best option I have so far. I think survey gives the impression of a large scale exploration, asking questions of random people, whereas assessment gives the impression of a 1-on-1 session where they evaluate the individual.

**Comment by nikw92** [comment]
Fair enough. But, assessment sounds like some kind of test to me. What charities are really getting is just some feedback. You could even just call the meetings as feedback. Anyway, it's just a trivial semantics issue. I'm fine with whatever you settle for :+1:

**Comment by drimpact** [comment]
Worked up a rough static design for this: https://gist.github.com/drimpact/cb947ed722bab9b224288ce6b34a41a0

**Comment by drimpact** [comment]
Progress has been made, but putting this to the side for a moment due to changing priorities. Current work can be found in branch 108
