### ISSUE TITLE
Assessment answer GA events

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#110]
To understand the use of the web app, we need to track events on certain actions. We use google analytics and https://github.com/react-ga/react-ga. Details about event tracking are available at https://github.com/react-ga/react-ga#reactgaeventargs. Google Analytics Debugger is good for verifying.

 - When a question is answered within a meeting, log an event. This should have a category of "assessment", action of "answered" and label should be "likert"

**Comment by abhishek71994** [comment]
a little more detail about this one? Seems interesting, would like to work on it

**Comment by drimpact** [comment]
You can see other examples of event tracking by searching the codebase for `ReactGA.event`. This should be within the `Meeting` container. I am happy to answer any specific questions.

**Comment by abhishek71994** [comment]
I saw a video in which the developer kept track of a certain link which was clicked in his react application. The issue asks the same thing similar to be happening, I presume? When a particular answer is answered it should be tracked in Google Analytics?

**Comment by drimpact** [comment]
Yes correct. When someone answers a question we are going log an event to google analytics so we can understand what users are up to on the app.
