### ISSUE TITLE
Visualisation Control Panel GA Events

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#111]
To understand the use of the web app, we need to track events on certain actions. We use google analytics and https://github.com/react-ga/react-ga. Details about event tracking are available at https://github.com/react-ga/react-ga#reactgaeventargs. Google Analytics Debugger is good for verifying.

 - When the visualisation is changed, log an event. This should have a category of "visualisation", action of "changed", label should be the selected visualisation (i.e. radar or table)
 - When the aggregation is changed, log an event. This should have a category of "aggregation", action of "changed", label should be the selected aggregation (i.e. questions or categories)

**Comment by abhishek71994** [comment]
I'll work on this as well.
