### ISSUE TITLE
Service report duration GA event

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#112]
To understand the use of the web app, we need to track events on certain actions. We use google analytics and https://github.com/react-ga/react-ga. Details about event tracking are available at https://github.com/react-ga/react-ga#reactgaeventargs. Google Analytics Debugger is good for verifying.

 - When a service report is viewed it would be useful to understand the time range people are viewing. Log an event with category of "servicereport", action of "range", value should be the time range rounded to the nearest number of weeks.

**Comment by abhishek71994** [comment]
@drimpact Can you tell a bit more about this issue? I'd like to work on this.

**Comment by drimpact** [comment]
It is very similar to the last story you did, tracking events to google analytics. Instead this time it is tracking the length of the time range selected for the service report. This will be interesting to see how people are using the reporting feature.

**Comment by abhishek71994** [comment]
It's gonna be in ServiceReport container I presume? What is required to be done? Return for how long the user was on that particular service report?

**Comment by drimpact** [comment]
When generating the report, users can specify the time range the report should cover. This event should record the amount of time the user has generated the report over.

**Comment by abhishek71994** [comment]
Is that a feature that is already there? The facility of a user specifying the time range?

**Comment by drimpact** [comment]
Yes

**Comment by abhishek71994** [comment]
So let me get this straight, the user will be setting the time range and all that needs to be done is using reactga.event an event has to be logged in.. ?
