### ISSUE TITLE
Update auth0 lock

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#162]
The old version of lock is being deprecated

**Comment by abhishek71994** [comment]
Can I work on it? Like the other issues, can you give few pointers on how to get this done?

**Comment by drimpact** [comment]
Should just be a case of increasing the auth0 lock package number in package.json, then checking everything still works as expected

**Comment by abhishek71994** [comment]
On it.. and one more thing. I'll ask on gitter.

**Comment by drimpact** [comment]
Thanks @abhishek71994
