### ISSUE TITLE
Cannot remove description

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#209]
Cannot delete description from questions

**Comment by abhishek71994** [comment]
@drimpact steps to the recreation of the bug?

**Comment by drimpact** [comment]
Define a question with a description. Once saved, edit the question and try to remove the description,

**Comment by abhishek71994** [comment]
I went to setting then questionnaire, If I try to change the description there is that what you mean?

**Comment by drimpact** [comment]
That is right, editing a description to another string will work, but trying to edit the description to an empty string (i.e. removing the description) does not.

**Comment by abhishek71994** [comment]
Hey did you fix this? Cz it seems to be working on my machine

**Comment by drimpact** [comment]
Solving in the backend...
