### ISSUE TITLE
SettingQuestionsInner: setState on an unmounted component

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#345]
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Formik (created by WithFormik(InnerForm))
    in WithFormik(InnerForm) (created by SettingQuestionsInner)
    in div (created by MessageContent)
    in MessageContent (created by SettingQuestionsInner)
    in div (created by Message)
    in Message (created by SettingQuestionsInner)
&nbsp;/app.js:55054 printWarning()
&nbsp;/app.js:55078 warning()
&nbsp;/app.js:133407 warnAboutUpdateOnUnmounted()

**Comment by themakshter** [comment]
From testing, I can see that this happens the first time you create a questionnaire on the questionnaires page. This will happen on the first successful questionnaire creation after a refresh of the page.
