### ISSUE TITLE
Add link to view questionnaire from beneficiary records table

### ISSUE THREAD

**Issue by themakshter** [impactasaurus/app#360]
When we view beneficiary records in the table, we can see the questionnaire name. However, do you think it's worth adding a link to allow users to just view the questionnaire itself and make changes to it if needed? Adding image in question to clarify where I mean:

![image](https://user-images.githubusercontent.com/2033876/46898726-8dcf2280-ce83-11e8-87b4-65509b377bcd.png)

**Comment by drimpact** [comment]
I like it :+1:, great idea, thanks

**Comment by drimpact** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [General refinement](https://trello.com/c/EQT3VeXW/50-general-refinement)
