### ISSUE TITLE
Indicate that the question set is automatically saved

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#46]
It is not clear that the question set is saved automatically to users. Make it clearer using some sort of visual indicator. 

I believe I have seen some sites show little symbols when it has been saved or just a label stating it is saved automatically.

**Comment by wilsonkasey** [comment]
I can do this.

**Comment by themakshter** [comment]
I guess no progress on this, so I'll take a stab at it

**Comment by themakshter** [comment]
Could you clarify what exactly is a question set? I had trouble figuring out which component it was.

**Comment by drimpact** [comment]
I think with the changes to the questionnaire page lately this has been completed. Will raise another issue to cover what remains
