### ISSUE TITLE
Allow users to be removed from organisation

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#494]
In the user list, allow users to be removed using mutations added in impactasaurus/server#237

**Comment by drimpact** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User Management](https://trello.com/c/JlfQZX43/62-user-management)

**Comment by abhishek71994** [comment]
I can take this up.

**Comment by drimpact** [comment]
Thanks for the offer @abhishek71994, there is user demand for this, so I will be pushing forward with it. I would appreciate your help elsewhere tho, lets chat about things you could work on.
