### ISSUE TITLE
updateOrgSetting failed: not found

### ISSUE THREAD

**Issue by k-l-reid** [impactasaurus/app#507]
Under settings, then the organisation tab, tick the checkbox for 'show beneficiary suggestions'. When save is clicked, a message is displayed saying 'Failed to save, please try refreshing'. This was found using my personal user account.

Response from server is as follows:

```
{
	"data": {
		"updateOrgSetting": null
	},
	"errors": [
		{
			"message": "not found",
			"locations": [
				{
					"line": 2,
					"column": 3
				}
			],
			"path": [
				"updateOrgSetting"
			]
		}
	]
}
```

**Comment by drimpact** [comment]
Thanks @k-l-reid. It turned out the organisation assigned to your account was not present in the database. I have created this and ensured it doesn't affect other customers.
