### ISSUE TITLE
Review: Pressing enter should submit beneficiary ID

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#57]
When on the review page, typing in a beneficiary ID, then pressing enter/return should be the same as pressing the 'Review' button.

**Comment by pranay414** [comment]
@drimpact I am working on this issue.

**Comment by drimpact** [comment]
I think semantic UI supports this with the form component, see : https://react.semantic-ui.com/collections/form. I think I should have been wrapping all the inputs with the form component

**Comment by nikw92** [comment]
Is it necessary to wrap in form? Doesn't Button have the 'onKeyPress' handler. I was specifically looking at this example and even tried doing it this way but it isn't working. Here is the relevant link: https://react.semantic-ui.com/elements/button#button-example-attached-events

**Comment by drimpact** [comment]
I suppose you would have to listen to a `onKeyPress` on the input field rather than the button. That could work too.

**Comment by nikw92** [comment]
That doesn't seem to be working either. I even tried displaying a simple alert message like "Enter Key pressed" but nothing seems to be happening. I'm testing using the latest Google Chrome 64 Bit version Here is the relevant code --

```
// Function that checks whether Enter key was pressed, if so, it then calls review()
private handleKeyPress(event: KeyboardEvent) {
    if(event.keyCode === 13) {
      this.review();
    }
}

// Listening for keypress in Input field
<Input type="text" placeholder="Beneficiary ID" onChange={this.setBenID} onKeyPress={this.handleKeyPress}/>
```

**Comment by nikw92** [comment]
Need a little bit of help with this issue. I tried listening on input field as well as button but it doesn't seem to work.
