### ISSUE TITLE
Question Set GA Events

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#59]
To understand the use of the web app, we need to track events on certain actions. We use google analytics and https://github.com/react-ga/react-ga. Details about event tracking are available at https://github.com/react-ga/react-ga#reactgaeventargs. Google Analytics Debugger is good for verifying.

1) When a question set is created, log an event. This should have a category of "questionset", action of "created", there should be no label.

2) When a question set is deleted, log an event. This should have a category of "questionset", action of "deleted", there should be no label.

**Comment by tomdohnal** [comment]
Working on this issue.
