### ISSUE TITLE
Question GA Events

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#60]
To understand the use of the web app, we need to track events on certain actions. We use google analytics and https://github.com/react-ga/react-ga. Details about event tracking are available at https://github.com/react-ga/react-ga#reactgaeventargs. Google Analytics Debugger is good for verifying.

1) When a question is created, log an event. This should have a category of "question", action of "created", label should be the question type (at the moment we only support 'likert' questions, so all labels should be 'likert').

2) When a question is deleted, log an event. This should have a category of "question", action of "deleted", label should be the question type (at the moment we only support 'likert' questions, so all labels should be 'likert').

3) When a category is set for a question, log an event. This should have a category of "question", action of "categorised", there should be no label

4) When a category is removed for a question, log an event. This should have a category of "question", action of "uncategorised", there should be no label

**Comment by tomdohnal** [comment]
Will do this one.

**Comment by tomdohnal** [comment]
What about when a category is changed? Should we log that as well?

**Comment by drimpact** [comment]
Sounds great. As much information as possible 😀On 8 Sep 2017 8:19 p.m., tomdohnal <notifications@github.com> wrote:What about when a category is changed? Should we log that as well?
