### ISSUE TITLE
Show 'recent activity' or truncated list of recorded meetings that can be navigated through in Review page

### ISSUE THREAD

**Issue by codespook** [impactasaurus/app#61]
While exploring the website, I noticed that the user has to manually look up a beneficiary by ID when reviewing previously recorded meetings. I think it would be useful to have a truncated list of meetings show up by default, say 10 items or more which can navigated through. The bottom section should have either page numbers and buttons for 'next' and 'previous' pages. The beneficiary ID look up can be left intact as it is still useful if the list of recorded meetings is large.

**Comment by drimpact** [comment]
Need to discuss with customers whether there is privacy concerns with this. If a charity worker was navigating the website with a beneficiary, would this leak information the beneficiary should not have seen?

I suppose this comes down to how sensitive the meetings are and whether the information displayed / the beneficiary IDs could personally identify someone.

**Comment by nikw92** [comment]
Perhaps we could make the whole table visible only when the mouse pointer hovers over it. In the default view we could populate it's fields with a bunch of Xs or whatever character/symbol you like. 

I was actually going to propose that we also add a feature to conduct meetings remotely. That is, the user could enter the beneficiary's email address and then a unique link would be mailed to the beneficiary which upon visiting, would enable him/her to complete a meeting/survey at his own time and pace.

**Comment by drimpact** [comment]
Very nice solution to the problem. 
I really like the email concept too, any chance you could write up an issue describing it?
I will run both ideas by my charity contact and see what she thinks.

**Comment by nikw92** [comment]
Sounds good. Posted this in an issue as requested. See #75

**Comment by drimpact** [comment]
Decided to archive this for the time being. I think something like this is required, but still discovering what users want in terms of a home screen.
