### ISSUE TITLE
Sortable service report table

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#67]
The table within the service report is sorted by the difference. It would be nice to allow users to sort by any column.

This is capable with semantic ui react, see : https://react.semantic-ui.com/collections/table#table-example-sortable

**Comment by abhishek71994** [comment]
I have a fair idea of doing this. Assign it to me. I just wanted to ask if its alright if I introduce a state in the ImpactTable component which will help track whether the rows are in asc or desc.
