### ISSUE TITLE
Enable users to send meeting/survey invites to beneficiaries via email

### ISSUE THREAD

**Issue by nikw92** [impactasaurus/app#75]
Currently users either have to conduct meetings/surveys in person with their beneficiaries or store their beneficiary's responses to survey questions somewhere else (for example, on a piece of paper) and then manually fill out the survey in Impactasaurus later.

I think it would be nice to have a feature that enables sending meeting/survey invites to beneficiaries which they could complete at their own time and pace. I'm thinking that we could have another input field in the 'Record' tab coupled with an 'invite' button and a question set selection dropdown menu where the user could enter a beneficiary's email address, select a question set and upon clicking invite, a unique link would be sent to the beneficiary's email address which they could visit to complete the question set that the user assigned them.

**Comment by nikw92** [comment]
Any update on this issue? Would the clients like it or not?

**Comment by drimpact** [comment]
I spoke to one charity today which would like this functionality. Will start thinking about when and how we achieve it.

**Comment by drimpact** [comment]
There is now a feature which allows the generation of links for beneficiaries to complete meetings. Although email is not built into impactasaurus, I think this solution solves this for now. Maybe later we could consider adding in built emailing if there is good uptake of the link feature.
