### ISSUE TITLE
ImpactTable: Limit the number of decimal points

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#85]
The impact table used in the review and report pages currently doesn't limit the number of decimal points displayed for values in the initial, latest and delta columns.

Adjust this so that numbers are shown with up to 2 decimal points.

**Comment by nikw92** [comment]
I would like to take this but what exactly do you mean by impact table?

**Comment by drimpact** [comment]
It is a newish component within the web app. See https://github.com/impactasaurus/app/tree/master/src/app/components/ImpactTable. It is used in the report and review pages to display initial and latest results for a question/category along with the difference between the initial and latest.

**Comment by wilsonkasey** [comment]
I can also work on this issue. If someone can contact me about this issue and how to approach it, that would be most appreciated. Thank you!

**Comment by drimpact** [comment]
Think you may  be a little late @wilsonkasey, looks like @nikw92 has pretty much completed it
