### ISSUE TITLE
Hide menu when not logged in

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#91]
Hide the main menu (purple menu at the top of the screen) items when the user is not logged in. Has become a bit more obvious now there is a log out button.

**Comment by abhishek71994** [comment]
Can I work on this? I would like to give this a go.

**Comment by drimpact** [comment]
@abhishek71994 please do! I have sent you an invite to the impactasaurus org.

**Comment by themakshter** [comment]
the way I see it, we could have a button in the middle called `Impactasaurus` which will normally redirect to `/` or `/login` if the user has not logged in. 

While the user is not logged in, there is only one link on the header :  the `Impactasaurus` title link in the middle of the page.  While the user is logged in, all the menu items i.e. `Home`, `Record`, `Review`, `Report`, `Settings` and `Log Out` should be visible. This is in addition to the normal one in the middle. That is my opinion on this but maybe @drimpact can add some more preferences.

**Comment by abhishek71994** [comment]
yeah I got it. I'll try and get it done.

**Comment by drimpact** [comment]
Sounds good! We may have to consider the responsiveness of the menu next, as the number of items are growing, but that can be a separate issue.

**Comment by drimpact** [comment]
@abhishek71994, the user's ID and logged in state is now in the redux store. An example of connecting this data into a component's props can be seen in the isLoggedIn component (https://github.com/impactasaurus/app/blob/master/src/app/components/IsLoggedIn/index.tsx#L28). I hope that does the trick :+1:
