### ISSUE TITLE
Responsive Main Menu

### ISSUE THREAD

**Issue by drimpact** [impactasaurus/app#96]
The main menu at the top of the screen is not responsive enough. On phone screens you cannot see all the buttons. It is common for menus like this to change to a burger menu on small screens.

Implement a system like this. We may have to move from semantic UI.

The current button highlighting and button hiding whilst logged out should continue to work.

**Comment by themakshter** [comment]
https://github.com/Semantic-Org/Semantic-UI/issues/3588 we might instead just do it the way they suggest: hide the sticky navbar and use the side bar instead when on smaller screens, instead of having to move away from Semantic UI

**Comment by drimpact** [comment]
Nice find @themakshter - looks like a good solution :+1:

**Comment by abhishek71994** [comment]
I could try it out. All though I tried and failed in implementing this a few months ago. But I've improved.

**Comment by themakshter** [comment]
It would need to be something like an option set in the header component to only change the way the list is created, nothing more should be changed. It will be interesting. I can also try checking out and see which way is the best.

**Comment by chimsgraphic** [comment]
I'm building a platform with semantic ui and I noticed this too. I still like Semantic ui, maybe I will try what was suggested.

**Comment by chimsgraphic** [comment]
In short, no need. I will just customize responsiveness with CSS.

**Comment by abhishek71994** [comment]
Any chance this is taken by someone. I would finally like to work on a frontend issue of impactasaurus.

**Comment by drimpact** [comment]
doesn't look like it :)

**Comment by abhishek71994** [comment]
Can I use basic css or should I try and find a Semantic ui Solution? I'm searching for the second one as I feel that a more generalized one but just wanted to make things clear.

**Comment by themakshter** [comment]
I think trying to find a Semantic UI solution would be best

**Comment by drimpact** [comment]
Decided to keep this simple, now the menu will fallback to icons on smaller screens.

**Comment by themakshter** [comment]
Sounds good
