### ISSUE TITLE
Add a button to go back to review page when viewing results of a look up

### ISSUE THREAD

**Issue by nikw92** [impactasaurus/app#97]
When a user enters a beneficiary ID and gets directed to the result page, It's not immediately clear what they should do to look up another beneficiary. Most may figure out that they need to click on the 'Review' tab again to look up another beneficiary or they may simply click on the browser's 'back' button. However, to make it more clear to them and provide a better user experience, we should consider adding a button with a descriptive title like 'back to review' or 'look up another beneficiary'. Do Let me know what you people think.

**Comment by Remorax** [comment]
I would like to work on this. Please assign it to me :)

**Comment by nikw92** [comment]
@Remorax  I think you'd need to be added to the project org to be assigned this issue. @drimpact will do so soon.
